---
layout: default
title: DeepONet for Burgers Equation
---

# Learning the 1+2D Burgers Equation with DeepONets

This project implements a Deep Operator Network (DeepONet) to learn the solution operator of the 1+2 dimensional viscous Burgers equation.

The goal is to learn the mapping:

\[
\mathcal{G}: u_0(x,y) \mapsto u(x,y,t)
\]

where \(u_0(x,y)\) is the initial condition and \(u(x,y,t)\) is the solution of the Burgers PDE.

---

## 1. The PDE

We consider the viscous Burgers equation:

\[
\partial_t u + u \cdot \nabla u = \nu \Delta u
\]

where:

- \(u = u(x,y,t)\)
- \(\nu\) is the viscosity
- \(\Delta\) is the Laplacian

This nonlinear PDE models convection–diffusion phenomena and shock formation.

---

## 2. Why Operator Learning?

Traditional solvers compute:

\[
u(x,y,t) \text{ for one initial condition}
\]

DeepONets aim to learn the **entire solution operator**:

\[
\mathcal{G}(u_0)
\]

Once trained, the network can predict solutions for unseen initial conditions without solving the PDE again.

---

## 3. DeepONet Architecture

The model consists of two neural networks:

### Branch Network
Encodes the initial condition \(u_0(x,y)\).

### Trunk Network
Encodes query coordinates \((x,y,t)\).

The final output is:

\[
u_\theta(x,y,t) = \sum_{k=1}^{p} b_k(u_0)\, t_k(x,y,t)
\]

where:
- \(b_k\) are branch outputs
- \(t_k\) are trunk outputs

This structure enables function-to-function learning.

---

## 4. Dataset Generation

Training data is generated by:

1. Sampling random smooth initial conditions
2. Solving the Burgers PDE numerically
3. Storing solution snapshots at multiple time steps

This produces supervised pairs:

\[
(u_0, (x,y,t), u(x,y,t))
\]

---

## 5. Training Objective

The model is trained using mean squared error:

\[
\mathcal{L} = \frac{1}{N} \sum |u_\theta - u_{\text{true}}|^2
\]

Generalization is evaluated on unseen initial conditions.

---

## 6. Results

The DeepONet successfully:

- Learns nonlinear convection–diffusion dynamics
- Generalizes to unseen initial conditions
- Captures shock-like structures
- Approximates the full operator mapping

### Example Prediction

(Add figure here)

---

## 7. Code Structure
